radp:
  env: local
  log:
    debug: false
    level: info
    file: $HOME/logs/radp/radp_bash.log
    rolling-policy:
      enabled: true
      max-history: 7
      total-size-cap: 5GB
      max-file-size: 10MB
  user:
    config:
      automap: true
