radp:
  env: dev
  log:
    debug: false
    level: info
    file: $HOME/logs/radp_bash.log
    rolling-policy:
      enabled: true
      max-history: 7
      total-size-cap: 5GB
      max-file-size: 10MB
    pattern:
      console: #todo 控制台日志支持颜色
      file: #todo
  user:
    config:
      automap: true
      path: # todo 需要支持相对路径
      filename: config.yaml
