radp:
  env: default
  auto: false
  framework:
    config:
      path: #todo
      filename: framework_config.yaml
    log:
      debug: false
      level: info
      file: $HOME/logs/radp_bash.log
      rolling-policy:
        enabled: true
        max-history: 7
        total-size-cap: 5GB
        max-file-size: 10MB
      pattern:
        console: #todo 控制台日志支持颜色
        file: #todo
  user:
    config:
      path: ${radp.framework.config.path}/../config
      filename: config.yaml
