radp:
  env: default
  log:
    debug: false
    level: info
    file: $HOME/logs/radp_bash.log
    rolling-policy:
      enabled: true
      max-history: 7
      total-size-cap: 5GB
      max-file-size: 10MB
    pattern:
      console: #todo 控制台日志支持颜色
      file: #todo
  user:
    config:
      automap: true
      path: ${radp.framework.config.path}/../config
      # config.yaml automap to config.sh,
      # if filename is user_config.yaml then automap to user_config.sh
      filename: config.yaml
